In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
import pandas as pd
import numpy as np

In [2]:
movies=pd.read_csv("/kaggle/input/tmdb-movie-metadata/tmdb_5000_movies.csv")
credits=pd.read_csv("/kaggle/input/tmdb-movie-metadata/tmdb_5000_credits.csv")

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
movies.shape

(4803, 20)

In [5]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
movies=movies.merge(credits,left_on='id',right_on='movie_id')

In [7]:
movies.drop(columns=['title_y','movie_id'],inplace=True)
movies.rename(columns={'title_x':'title'},inplace=True)

# **Features That Can Act As TAGS**

In [57]:
#genres
#id-to make website
#keywords
#title
#Overview
#cast
#crew

movies=movies[['genres','id','keywords','title','overview','cast','crew']]

In [58]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   genres    4803 non-null   object
 1   id        4803 non-null   int64
 2   keywords  4803 non-null   object
 3   title     4803 non-null   object
 4   overview  4800 non-null   object
 5   cast      4803 non-null   object
 6   crew      4803 non-null   object
dtypes: int64(1), object(6)
memory usage: 262.8+ KB

In [59]:
movies.isnull().sum()

genres      0
id          0
keywords    0
title       0
overview    3
cast        0
crew        0
dtype: int64

In [8]:
movies.duplicated().sum()

0

In [9]:
movies.dropna(inplace=True)

In [10]:
import ast

In [11]:
def convert(list):
    L=[]
    for i in ast.literal_eval(list):
        L.append(i['name'])
    return L

In [12]:
movies['genres']=movies['genres'].apply(convert)

In [13]:
movies['keywords']=movies['keywords'].apply(convert)

In [15]:
def convert_(list):
    L=[]
    counter=0
    for i in ast.literal_eval(list):
        L.append(i['name'])
        counter=counter+1
        if counter==3:
            break
    return L

In [14]:
movies['cast']=movies['cast'].apply(convert_)

In [16]:
def convert1(list):
    L=[]
    for i in ast.literal_eval(list):
        if i['job']=='Director':
            L.append(i['name'])
            break
    return L

In [ ]:
movies['crew']=movies['crew'].apply(convert1)

In [18]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [19]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew
0,237000000,"[Action, Adventure, Fantasy, Science Fiction]",http://www.avatarmovie.com/,19995,"[culture clash, future, space war, space colon...",en,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,300000000,"[Adventure, Fantasy, Action]",http://disney.go.com/disneypictures/pirates/,285,"[ocean, drug abuse, exotic island, east india ...",en,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,"[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,245000000,"[Action, Adventure, Crime]",http://www.sonypictures.com/movies/spectre/,206647,"[spy, based on novel, secret agent, sequel, mi...",en,Spectre,"[A, cryptic, message, from, Bond’s, past, send...",107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,250000000,"[Action, Crime, Drama, Thriller]",http://www.thedarkknightrises.com/,49026,"[dc comics, crime fighter, terrorist, secret i...",en,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...",112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,260000000,"[Action, Adventure, Science Fiction]",http://movies.disney.com/john-carter,49529,"[based on novel, mars, medallion, space travel...",en,John Carter,"[John, Carter, is, a, war-weary,, former, mili...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,"[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [20]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [21]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [22]:
final_df=movies[['id','title','tags']]

In [23]:
final_df

,id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4773,2292,Clerks,"[Convenience, and, video, store, clerks, Dante..."
4781,255266,Dry Spell,"[Sasha, tries, to, get, her, soon-to-be, ex, h..."
4791,157185,Tin Can Man,"[Recently, dumped, by, his, girlfirend, for, a..."
4796,14337,Primer,"[Friends/fledgling, entrepreneurs, invent, a, ..."
4801,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."

In [24]:
final_df['tags']=final_df['tags'].apply(lambda x:" ".join(x))

/tmp/ipykernel_35/142005878.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['tags']=final_df['tags'].apply(lambda x:" ".join(x))

In [25]:
final_df

,id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...,...
4773,2292,Clerks,Convenience and video store clerks Dante and R...
4781,255266,Dry Spell,Sasha tries to get her soon-to-be ex husband K...
4791,157185,Tin Can Man,Recently dumped by his girlfirend for another ...
4796,14337,Primer,Friends/fledgling entrepreneurs invent a devic...
4801,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...

In [26]:
final_df[final_df['title']=='Avatar'].index.item()

0

In [27]:
final_df['tags']=final_df['tags'].apply(lambda x:x.lower())

/tmp/ipykernel_35/3671300185.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['tags']=final_df['tags'].apply(lambda x:x.lower())

In [28]:
import nltk 
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [29]:
def stem(object):
    l=[]
    for i in object.split():
        l.append(ps.stem(i))

    return " ".join(l)

In [30]:
final_df['tags']=final_df['tags'].apply(stem)

/tmp/ipykernel_35/3542233429.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['tags']=final_df['tags'].apply(stem)

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
vec=CountVectorizer(max_features=5000,stop_words='english')

In [32]:
vectors=vec.fit_transform(final_df['tags']).toarray()

In [33]:
vec.get_feature_names_out()

array(['00', '000', '007', ..., 'zoo', 'zooey', 'zooeydeschanel'],
      dtype=object)

In [34]:
from sklearn.metrics.pairwise  import cosine_similarity
scores = cosine_similarity(vectors)

In [35]:
scores

array([[1.        , 0.07715167, 0.07938842, ..., 0.        , 0.048795  ,
        0.        ],
       [0.07715167, 1.        , 0.0571662 , ..., 0.03268602, 0.02635231,
        0.        ],
       [0.07938842, 0.0571662 , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.03268602, 0.        , ..., 1.        , 0.        ,
        0.1903749 ],
       [0.048795  , 0.02635231, 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.1903749 , 0.        ,
        1.        ]])

In [36]:
def recommend(movie):
    idx = final_df[final_df['title']==movie].index.item()
    L=[]
    for i in scores:
        L.append(i[idx])

    K= sorted(L,reverse=True)[1:6]
    L=[]
    for i in range(len(scores)):
        if scores[i][idx] in K:
            L.append(i)
    K=[]
    for i in L:
        K.append(final_df.iloc[i]['title'])

    return K

In [48]:
from sklearn.metrics.pairwise import cosine_distances
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import silhouette_score

# Use cosine distance instead of Euclidean
distance_matrix = cosine_distances(vectors)

# Agglomerative clustering using precomputed distances
model = AgglomerativeClustering(n_clusters=10, affinity='precomputed', linkage='average')
labels = model.fit_predict(distance_matrix)

# Silhouette Score using cosine distance
score = silhouette_score(vectors, labels, metric='cosine')
print("Silhouette Score (cosine):", score)

/usr/local/lib/python3.11/dist-packages/sklearn/cluster/_agglomerative.py:983: FutureWarning: Attribute `affinity` was deprecated in version 1.2 and will be removed in 1.4. Use `metric` instead
  warnings.warn(

Silhouette Score (cosine): 0.004524280627190215

In [50]:
from sklearn.decomposition import PCA

pca = PCA(n_components=100)
reduced_vectors = pca.fit_transform(vectors)

kmeans = KMeans(n_clusters=10, random_state=42)
labels = kmeans.fit_predict(reduced_vectors)

score = silhouette_score(reduced_vectors, labels)
print("Silhouette Score after PCA:", score)

/usr/local/lib/python3.11/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

Silhouette Score after PCA: 0.012565659203752027

In [46]:
recommend('Spectre')

['Quantum of Solace',
 'Skyfall',
 'Never Say Never Again',
 'Octopussy',
 'From Russia with Love']

In [145]:
import pickle

In [148]:
pickle.dump(final_df.to_dict(),open('movies.pkl','wb'))
pickle.dump(scores,open('score.pkl','wb'))